name: Update Adblock Filter

on:
  schedule:
    - cron: '0 0 1 * *' # 毎月1日の0:00 (UTC)に実行
  workflow_dispatch: # 手動で実行できるボタンも用意

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Download CSVs
        run: python download_csvs.py

      - name: Create Adblock filter
        run: python create_adblock_filter.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add adblock_filter.txt domains.txt hosts_filter.txt
          git commit -m "Auto-update adblock filter" || echo "No changes to commit"
          git push
